### ISSUE TITLE
Error at startup beta 1.4.8

### ISSUE THREAD

**Issue by KTownMods** [ohhsodead/ModioX#17]
Hey, i get this error, and cant click on any games always same error:

2020-11-21 23:15:19,427 [1] ERROR ModioX.Program - An unknown error occurred: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei ModioX.Models.Database.CategoriesData.<>c__DisplayClass12_0.<GetCategoryById>b__0(Category category)
   bei System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   bei ModioX.Models.Database.CategoriesData.GetCategoryById(String categoryId)
   bei ModioX.Forms.Windows.MainWindow.LoadInstalledGameMods()
   bei ModioX.Forms.Windows.MainWindow.LoadModsByCategoryId(String categoryId, String name, String firmware, String type, String region)
   bei ModioX.Forms.Windows.MainWindow.InitializeFinished(Object sender, RunWorkerCompletedEventArgs e)
   bei System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   bei System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)

**Comment by ohhsodead** [comment]
@KTownMods hey, thanks for reporting this issue. For me it looks like there is a problem loading the installed game mods. Please close the app and delete the SettingsData.json file inside Documents > ModioX folder. Restart and it them should work fine, only your settings will be set to default and it won't remember your installed game mods. I believe this issue is due to a mod being modified in the database and now can't be found.

**Comment by KTownMods** [comment]
thanks it works
